/**
 * This class is generated by jOOQ
 */
package diamond.cms.server.model.jooq;


import diamond.cms.server.model.jooq.tables.CArticle;
import diamond.cms.server.model.jooq.tables.CArticleTag;
import diamond.cms.server.model.jooq.tables.CCatalog;
import diamond.cms.server.model.jooq.tables.CTag;
import diamond.cms.server.model.jooq.tables.CUser;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Cms extends SchemaImpl {

	private static final long serialVersionUID = 363785501;

	/**
	 * The reference instance of <code>cms</code>
	 */
	public static final Cms CMS = new Cms();

	/**
	 * No further instances allowed
	 */
	private Cms() {
		super("cms");
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			CArticle.C_ARTICLE,
			CArticleTag.C_ARTICLE_TAG,
			CCatalog.C_CATALOG,
			CTag.C_TAG,
			CUser.C_USER);
	}
}
