/**
 * This class is generated by jOOQ
 */
package diamond.cms.server.model.jooq;


import diamond.cms.server.model.jooq.tables.CArticle;
import diamond.cms.server.model.jooq.tables.CArticleTag;
import diamond.cms.server.model.jooq.tables.CCatalog;
import diamond.cms.server.model.jooq.tables.CComment;
import diamond.cms.server.model.jooq.tables.CPageView;
import diamond.cms.server.model.jooq.tables.CSetting;
import diamond.cms.server.model.jooq.tables.CTag;
import diamond.cms.server.model.jooq.tables.CUser;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in cms
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table cms.c_article
	 */
	public static final CArticle C_ARTICLE = diamond.cms.server.model.jooq.tables.CArticle.C_ARTICLE;

	/**
	 * The table cms.c_article_tag
	 */
	public static final CArticleTag C_ARTICLE_TAG = diamond.cms.server.model.jooq.tables.CArticleTag.C_ARTICLE_TAG;

	/**
	 * The table cms.c_catalog
	 */
	public static final CCatalog C_CATALOG = diamond.cms.server.model.jooq.tables.CCatalog.C_CATALOG;

	/**
	 * The table cms.c_comment
	 */
	public static final CComment C_COMMENT = diamond.cms.server.model.jooq.tables.CComment.C_COMMENT;

	/**
	 * The table cms.c_page_view
	 */
	public static final CPageView C_PAGE_VIEW = diamond.cms.server.model.jooq.tables.CPageView.C_PAGE_VIEW;

	/**
	 * The table cms.c_setting
	 */
	public static final CSetting C_SETTING = diamond.cms.server.model.jooq.tables.CSetting.C_SETTING;

	/**
	 * The table cms.c_tag
	 */
	public static final CTag C_TAG = diamond.cms.server.model.jooq.tables.CTag.C_TAG;

	/**
	 * The table cms.c_user
	 */
	public static final CUser C_USER = diamond.cms.server.model.jooq.tables.CUser.C_USER;
}
