/**
 * This class is generated by jOOQ
 */
package diamond.cms.server.model.jooq;


import diamond.cms.server.model.jooq.tables.CArticle;
import diamond.cms.server.model.jooq.tables.CArticleTag;
import diamond.cms.server.model.jooq.tables.CCatalog;
import diamond.cms.server.model.jooq.tables.CComment;
import diamond.cms.server.model.jooq.tables.CEmailConfig;
import diamond.cms.server.model.jooq.tables.CEmailSend;
import diamond.cms.server.model.jooq.tables.CIpLocation;
import diamond.cms.server.model.jooq.tables.CKeyword;
import diamond.cms.server.model.jooq.tables.CPageView;
import diamond.cms.server.model.jooq.tables.CSetting;
import diamond.cms.server.model.jooq.tables.CTag;
import diamond.cms.server.model.jooq.tables.CUser;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in cms
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>cms.c_article</code>.
     */
    public static final CArticle C_ARTICLE = diamond.cms.server.model.jooq.tables.CArticle.C_ARTICLE;

    /**
     * The table <code>cms.c_article_tag</code>.
     */
    public static final CArticleTag C_ARTICLE_TAG = diamond.cms.server.model.jooq.tables.CArticleTag.C_ARTICLE_TAG;

    /**
     * The table <code>cms.c_catalog</code>.
     */
    public static final CCatalog C_CATALOG = diamond.cms.server.model.jooq.tables.CCatalog.C_CATALOG;

    /**
     * The table <code>cms.c_comment</code>.
     */
    public static final CComment C_COMMENT = diamond.cms.server.model.jooq.tables.CComment.C_COMMENT;

    /**
     * The table <code>cms.c_email_config</code>.
     */
    public static final CEmailConfig C_EMAIL_CONFIG = diamond.cms.server.model.jooq.tables.CEmailConfig.C_EMAIL_CONFIG;

    /**
     * The table <code>cms.c_email_send</code>.
     */
    public static final CEmailSend C_EMAIL_SEND = diamond.cms.server.model.jooq.tables.CEmailSend.C_EMAIL_SEND;

    /**
     * The table <code>cms.c_ip_location</code>.
     */
    public static final CIpLocation C_IP_LOCATION = diamond.cms.server.model.jooq.tables.CIpLocation.C_IP_LOCATION;

    /**
     * The table <code>cms.c_keyword</code>.
     */
    public static final CKeyword C_KEYWORD = diamond.cms.server.model.jooq.tables.CKeyword.C_KEYWORD;

    /**
     * The table <code>cms.c_page_view</code>.
     */
    public static final CPageView C_PAGE_VIEW = diamond.cms.server.model.jooq.tables.CPageView.C_PAGE_VIEW;

    /**
     * The table <code>cms.c_setting</code>.
     */
    public static final CSetting C_SETTING = diamond.cms.server.model.jooq.tables.CSetting.C_SETTING;

    /**
     * The table <code>cms.c_tag</code>.
     */
    public static final CTag C_TAG = diamond.cms.server.model.jooq.tables.CTag.C_TAG;

    /**
     * The table <code>cms.c_user</code>.
     */
    public static final CUser C_USER = diamond.cms.server.model.jooq.tables.CUser.C_USER;
}
