/**
 * This class is generated by jOOQ
 */
package diamond.cms.server.model.jooq.tables.pojos;


import diamond.cms.server.model.jooq.tables.interfaces.ICArticleTag;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CArticleTagPojo implements ICArticleTag {

    private static final long serialVersionUID = -317698674;

    private String articleId;
    private String tagId;

    public CArticleTagPojo() {}

    public CArticleTagPojo(CArticleTagPojo value) {
        this.articleId = value.articleId;
        this.tagId = value.tagId;
    }

    public CArticleTagPojo(
        String articleId,
        String tagId
    ) {
        this.articleId = articleId;
        this.tagId = tagId;
    }

    @NotNull
    @Size(max = 40)
    @Override
    public String getArticleId() {
        return this.articleId;
    }

    @Override
    public void setArticleId(String articleId) {
        this.articleId = articleId;
    }

    @NotNull
    @Size(max = 40)
    @Override
    public String getTagId() {
        return this.tagId;
    }

    @Override
    public void setTagId(String tagId) {
        this.tagId = tagId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CArticleTagPojo (");

        sb.append(articleId);
        sb.append(", ").append(tagId);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ICArticleTag from) {
        setArticleId(from.getArticleId());
        setTagId(from.getTagId());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ICArticleTag> E into(E into) {
        into.from(this);
        return into;
    }
}
