/**
 * This class is generated by jOOQ
 */
package diamond.cms.server.model.jooq.tables.pojos;


import diamond.cms.server.model.jooq.tables.interfaces.ICArticle;

import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CArticlePojo implements ICArticle {

	private static final long serialVersionUID = -1279499745;

	private String    id;
	private String    content;
	private Timestamp createtime;
	private String    title;
	private Timestamp updatetime;

	public CArticlePojo() {}

	public CArticlePojo(CArticlePojo value) {
		this.id = value.id;
		this.content = value.content;
		this.createtime = value.createtime;
		this.title = value.title;
		this.updatetime = value.updatetime;
	}

	public CArticlePojo(
		String    id,
		String    content,
		Timestamp createtime,
		String    title,
		Timestamp updatetime
	) {
		this.id = id;
		this.content = content;
		this.createtime = createtime;
		this.title = title;
		this.updatetime = updatetime;
	}

	@NotNull
	@Size(max = 255)
	@Override
	public String getId() {
		return this.id;
	}

	@Override
	public void setId(String id) {
		this.id = id;
	}

	@NotNull
	@Size(max = 65535)
	@Override
	public String getContent() {
		return this.content;
	}

	@Override
	public void setContent(String content) {
		this.content = content;
	}

	@NotNull
	@Override
	public Timestamp getCreatetime() {
		return this.createtime;
	}

	@Override
	public void setCreatetime(Timestamp createtime) {
		this.createtime = createtime;
	}

	@NotNull
	@Size(max = 255)
	@Override
	public String getTitle() {
		return this.title;
	}

	@Override
	public void setTitle(String title) {
		this.title = title;
	}

	@NotNull
	@Override
	public Timestamp getUpdatetime() {
		return this.updatetime;
	}

	@Override
	public void setUpdatetime(Timestamp updatetime) {
		this.updatetime = updatetime;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("CArticlePojo (");

		sb.append(id);
		sb.append(", ").append(content);
		sb.append(", ").append(createtime);
		sb.append(", ").append(title);
		sb.append(", ").append(updatetime);

		sb.append(")");
		return sb.toString();
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(ICArticle from) {
		setId(from.getId());
		setContent(from.getContent());
		setCreatetime(from.getCreatetime());
		setTitle(from.getTitle());
		setUpdatetime(from.getUpdatetime());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends ICArticle> E into(E into) {
		into.from(this);
		return into;
	}
}
