/**
 * This class is generated by jOOQ
 */
package diamond.cms.server.model.jooq.tables.pojos;


import diamond.cms.server.model.jooq.tables.interfaces.ICArticle;

import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CArticlePojo implements ICArticle {

    private static final long serialVersionUID = 1448540362;

    private String    id;
    private String    title;
    private String    content;
    private String    summary;
    private Integer   status;
    private Timestamp createTime;
    private Timestamp updateTime;
    private String    catalogId;
    private String    banner;
    private String    tagNames;

    public CArticlePojo() {}

    public CArticlePojo(CArticlePojo value) {
        this.id = value.id;
        this.title = value.title;
        this.content = value.content;
        this.summary = value.summary;
        this.status = value.status;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
        this.catalogId = value.catalogId;
        this.banner = value.banner;
        this.tagNames = value.tagNames;
    }

    public CArticlePojo(
        String    id,
        String    title,
        String    content,
        String    summary,
        Integer   status,
        Timestamp createTime,
        Timestamp updateTime,
        String    catalogId,
        String    banner,
        String    tagNames
    ) {
        this.id = id;
        this.title = title;
        this.content = content;
        this.summary = summary;
        this.status = status;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.catalogId = catalogId;
        this.banner = banner;
        this.tagNames = tagNames;
    }

    @NotNull
    @Size(max = 40)
    @Override
    public String getId() {
        return this.id;
    }

    @Override
    public void setId(String id) {
        this.id = id;
    }

    @NotNull
    @Size(max = 255)
    @Override
    public String getTitle() {
        return this.title;
    }

    @Override
    public void setTitle(String title) {
        this.title = title;
    }

    @Size(max = 65535)
    @Override
    public String getContent() {
        return this.content;
    }

    @Override
    public void setContent(String content) {
        this.content = content;
    }

    @Size(max = 300)
    @Override
    public String getSummary() {
        return this.summary;
    }

    @Override
    public void setSummary(String summary) {
        this.summary = summary;
    }

    @Override
    public Integer getStatus() {
        return this.status;
    }

    @Override
    public void setStatus(Integer status) {
        this.status = status;
    }

    @Override
    public Timestamp getCreateTime() {
        return this.createTime;
    }

    @Override
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    @Override
    public Timestamp getUpdateTime() {
        return this.updateTime;
    }

    @Override
    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    @Size(max = 40)
    @Override
    public String getCatalogId() {
        return this.catalogId;
    }

    @Override
    public void setCatalogId(String catalogId) {
        this.catalogId = catalogId;
    }

    @Size(max = 150)
    @Override
    public String getBanner() {
        return this.banner;
    }

    @Override
    public void setBanner(String banner) {
        this.banner = banner;
    }

    @Size(max = 300)
    @Override
    public String getTagNames() {
        return this.tagNames;
    }

    @Override
    public void setTagNames(String tagNames) {
        this.tagNames = tagNames;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CArticlePojo (");

        sb.append(id);
        sb.append(", ").append(title);
        sb.append(", ").append(content);
        sb.append(", ").append(summary);
        sb.append(", ").append(status);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(catalogId);
        sb.append(", ").append(banner);
        sb.append(", ").append(tagNames);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ICArticle from) {
        setId(from.getId());
        setTitle(from.getTitle());
        setContent(from.getContent());
        setSummary(from.getSummary());
        setStatus(from.getStatus());
        setCreateTime(from.getCreateTime());
        setUpdateTime(from.getUpdateTime());
        setCatalogId(from.getCatalogId());
        setBanner(from.getBanner());
        setTagNames(from.getTagNames());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ICArticle> E into(E into) {
        into.from(this);
        return into;
    }
}
