/**
 * This class is generated by jOOQ
 */
package diamond.cms.server.model.jooq.tables.pojos;


import diamond.cms.server.model.jooq.tables.interfaces.ICCatalog;

import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CCatalogPojo implements ICCatalog {

	private static final long serialVersionUID = -999747337;

	private String    id;
	private Timestamp createtime;
	private String    name;
	private Timestamp updatetime;
	private String    parentId;

	public CCatalogPojo() {}

	public CCatalogPojo(CCatalogPojo value) {
		this.id = value.id;
		this.createtime = value.createtime;
		this.name = value.name;
		this.updatetime = value.updatetime;
		this.parentId = value.parentId;
	}

	public CCatalogPojo(
		String    id,
		Timestamp createtime,
		String    name,
		Timestamp updatetime,
		String    parentId
	) {
		this.id = id;
		this.createtime = createtime;
		this.name = name;
		this.updatetime = updatetime;
		this.parentId = parentId;
	}

	@NotNull
	@Size(max = 255)
	@Override
	public String getId() {
		return this.id;
	}

	@Override
	public void setId(String id) {
		this.id = id;
	}

	@NotNull
	@Override
	public Timestamp getCreatetime() {
		return this.createtime;
	}

	@Override
	public void setCreatetime(Timestamp createtime) {
		this.createtime = createtime;
	}

	@NotNull
	@Size(max = 255)
	@Override
	public String getName() {
		return this.name;
	}

	@Override
	public void setName(String name) {
		this.name = name;
	}

	@NotNull
	@Override
	public Timestamp getUpdatetime() {
		return this.updatetime;
	}

	@Override
	public void setUpdatetime(Timestamp updatetime) {
		this.updatetime = updatetime;
	}

	@Size(max = 255)
	@Override
	public String getParentId() {
		return this.parentId;
	}

	@Override
	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("CCatalogPojo (");

		sb.append(id);
		sb.append(", ").append(createtime);
		sb.append(", ").append(name);
		sb.append(", ").append(updatetime);
		sb.append(", ").append(parentId);

		sb.append(")");
		return sb.toString();
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(ICCatalog from) {
		setId(from.getId());
		setCreatetime(from.getCreatetime());
		setName(from.getName());
		setUpdatetime(from.getUpdatetime());
		setParentId(from.getParentId());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends ICCatalog> E into(E into) {
		into.from(this);
		return into;
	}
}
