/**
 * This class is generated by jOOQ
 */
package diamond.cms.server.model.jooq.tables.pojos;


import diamond.cms.server.model.jooq.tables.interfaces.ICComment;

import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CCommentPojo implements ICComment {

    private static final long serialVersionUID = 1428575756;

    private String    id;
    private String    articleId;
    private String    nickname;
    private String    email;
    private String    content;
    private Integer   state;
    private Timestamp createTime;
    private Timestamp updateTime;
    private String    ip;
    private String    replyId;
    private Boolean   fromAuthor;

    public CCommentPojo() {}

    public CCommentPojo(CCommentPojo value) {
        this.id = value.id;
        this.articleId = value.articleId;
        this.nickname = value.nickname;
        this.email = value.email;
        this.content = value.content;
        this.state = value.state;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
        this.ip = value.ip;
        this.replyId = value.replyId;
        this.fromAuthor = value.fromAuthor;
    }

    public CCommentPojo(
        String    id,
        String    articleId,
        String    nickname,
        String    email,
        String    content,
        Integer   state,
        Timestamp createTime,
        Timestamp updateTime,
        String    ip,
        String    replyId,
        Boolean   fromAuthor
    ) {
        this.id = id;
        this.articleId = articleId;
        this.nickname = nickname;
        this.email = email;
        this.content = content;
        this.state = state;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.ip = ip;
        this.replyId = replyId;
        this.fromAuthor = fromAuthor;
    }

    @NotNull
    @Size(max = 40)
    @Override
    public String getId() {
        return this.id;
    }

    @Override
    public void setId(String id) {
        this.id = id;
    }

    @NotNull
    @Size(max = 40)
    @Override
    public String getArticleId() {
        return this.articleId;
    }

    @Override
    public void setArticleId(String articleId) {
        this.articleId = articleId;
    }

    @NotNull
    @Size(max = 50)
    @Override
    public String getNickname() {
        return this.nickname;
    }

    @Override
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    @NotNull
    @Size(max = 50)
    @Override
    public String getEmail() {
        return this.email;
    }

    @Override
    public void setEmail(String email) {
        this.email = email;
    }

    @Size(max = 512)
    @Override
    public String getContent() {
        return this.content;
    }

    @Override
    public void setContent(String content) {
        this.content = content;
    }

    @Override
    public Integer getState() {
        return this.state;
    }

    @Override
    public void setState(Integer state) {
        this.state = state;
    }

    @Override
    public Timestamp getCreateTime() {
        return this.createTime;
    }

    @Override
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    @Override
    public Timestamp getUpdateTime() {
        return this.updateTime;
    }

    @Override
    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    @NotNull
    @Size(max = 40)
    @Override
    public String getIp() {
        return this.ip;
    }

    @Override
    public void setIp(String ip) {
        this.ip = ip;
    }

    @Size(max = 40)
    @Override
    public String getReplyId() {
        return this.replyId;
    }

    @Override
    public void setReplyId(String replyId) {
        this.replyId = replyId;
    }

    @Override
    public Boolean getFromAuthor() {
        return this.fromAuthor;
    }

    @Override
    public void setFromAuthor(Boolean fromAuthor) {
        this.fromAuthor = fromAuthor;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CCommentPojo (");

        sb.append(id);
        sb.append(", ").append(articleId);
        sb.append(", ").append(nickname);
        sb.append(", ").append(email);
        sb.append(", ").append(content);
        sb.append(", ").append(state);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(ip);
        sb.append(", ").append(replyId);
        sb.append(", ").append(fromAuthor);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ICComment from) {
        setId(from.getId());
        setArticleId(from.getArticleId());
        setNickname(from.getNickname());
        setEmail(from.getEmail());
        setContent(from.getContent());
        setState(from.getState());
        setCreateTime(from.getCreateTime());
        setUpdateTime(from.getUpdateTime());
        setIp(from.getIp());
        setReplyId(from.getReplyId());
        setFromAuthor(from.getFromAuthor());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ICComment> E into(E into) {
        into.from(this);
        return into;
    }
}
