/**
 * This class is generated by jOOQ
 */
package diamond.cms.server.model.jooq.tables.pojos;


import diamond.cms.server.model.jooq.tables.interfaces.ICEmailConfig;

import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CEmailConfigPojo implements ICEmailConfig {

    private static final long serialVersionUID = 1136790912;

    private String    id;
    private String    smtpHost;
    private Integer   smtpPort;
    private Boolean   sslEnable;
    private String    emailAccount;
    private String    emailPassword;
    private Boolean   enable;
    private Timestamp createTime;

    public CEmailConfigPojo() {}

    public CEmailConfigPojo(CEmailConfigPojo value) {
        this.id = value.id;
        this.smtpHost = value.smtpHost;
        this.smtpPort = value.smtpPort;
        this.sslEnable = value.sslEnable;
        this.emailAccount = value.emailAccount;
        this.emailPassword = value.emailPassword;
        this.enable = value.enable;
        this.createTime = value.createTime;
    }

    public CEmailConfigPojo(
        String    id,
        String    smtpHost,
        Integer   smtpPort,
        Boolean   sslEnable,
        String    emailAccount,
        String    emailPassword,
        Boolean   enable,
        Timestamp createTime
    ) {
        this.id = id;
        this.smtpHost = smtpHost;
        this.smtpPort = smtpPort;
        this.sslEnable = sslEnable;
        this.emailAccount = emailAccount;
        this.emailPassword = emailPassword;
        this.enable = enable;
        this.createTime = createTime;
    }

    @NotNull
    @Size(max = 40)
    @Override
    public String getId() {
        return this.id;
    }

    @Override
    public void setId(String id) {
        this.id = id;
    }

    @NotNull
    @Size(max = 45)
    @Override
    public String getSmtpHost() {
        return this.smtpHost;
    }

    @Override
    public void setSmtpHost(String smtpHost) {
        this.smtpHost = smtpHost;
    }

    @NotNull
    @Override
    public Integer getSmtpPort() {
        return this.smtpPort;
    }

    @Override
    public void setSmtpPort(Integer smtpPort) {
        this.smtpPort = smtpPort;
    }

    @Override
    public Boolean getSslEnable() {
        return this.sslEnable;
    }

    @Override
    public void setSslEnable(Boolean sslEnable) {
        this.sslEnable = sslEnable;
    }

    @NotNull
    @Size(max = 60)
    @Override
    public String getEmailAccount() {
        return this.emailAccount;
    }

    @Override
    public void setEmailAccount(String emailAccount) {
        this.emailAccount = emailAccount;
    }

    @NotNull
    @Size(max = 60)
    @Override
    public String getEmailPassword() {
        return this.emailPassword;
    }

    @Override
    public void setEmailPassword(String emailPassword) {
        this.emailPassword = emailPassword;
    }

    @Override
    public Boolean getEnable() {
        return this.enable;
    }

    @Override
    public void setEnable(Boolean enable) {
        this.enable = enable;
    }

    @Override
    public Timestamp getCreateTime() {
        return this.createTime;
    }

    @Override
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CEmailConfigPojo (");

        sb.append(id);
        sb.append(", ").append(smtpHost);
        sb.append(", ").append(smtpPort);
        sb.append(", ").append(sslEnable);
        sb.append(", ").append(emailAccount);
        sb.append(", ").append(emailPassword);
        sb.append(", ").append(enable);
        sb.append(", ").append(createTime);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ICEmailConfig from) {
        setId(from.getId());
        setSmtpHost(from.getSmtpHost());
        setSmtpPort(from.getSmtpPort());
        setSslEnable(from.getSslEnable());
        setEmailAccount(from.getEmailAccount());
        setEmailPassword(from.getEmailPassword());
        setEnable(from.getEnable());
        setCreateTime(from.getCreateTime());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ICEmailConfig> E into(E into) {
        into.from(this);
        return into;
    }
}
