/**
 * This class is generated by jOOQ
 */
package diamond.cms.server.model.jooq.tables.pojos;


import diamond.cms.server.model.jooq.tables.interfaces.ICEmailSend;

import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CEmailSendPojo implements ICEmailSend {

    private static final long serialVersionUID = 172335789;

    private String    id;
    private String    fromEmail;
    private String    toEmail;
    private String    title;
    private String    content;
    private String    remark;
    private String    emailConfigId;
    private Timestamp createTime;

    public CEmailSendPojo() {}

    public CEmailSendPojo(CEmailSendPojo value) {
        this.id = value.id;
        this.fromEmail = value.fromEmail;
        this.toEmail = value.toEmail;
        this.title = value.title;
        this.content = value.content;
        this.remark = value.remark;
        this.emailConfigId = value.emailConfigId;
        this.createTime = value.createTime;
    }

    public CEmailSendPojo(
        String    id,
        String    fromEmail,
        String    toEmail,
        String    title,
        String    content,
        String    remark,
        String    emailConfigId,
        Timestamp createTime
    ) {
        this.id = id;
        this.fromEmail = fromEmail;
        this.toEmail = toEmail;
        this.title = title;
        this.content = content;
        this.remark = remark;
        this.emailConfigId = emailConfigId;
        this.createTime = createTime;
    }

    @NotNull
    @Size(max = 40)
    @Override
    public String getId() {
        return this.id;
    }

    @Override
    public void setId(String id) {
        this.id = id;
    }

    @NotNull
    @Size(max = 45)
    @Override
    public String getFromEmail() {
        return this.fromEmail;
    }

    @Override
    public void setFromEmail(String fromEmail) {
        this.fromEmail = fromEmail;
    }

    @NotNull
    @Size(max = 45)
    @Override
    public String getToEmail() {
        return this.toEmail;
    }

    @Override
    public void setToEmail(String toEmail) {
        this.toEmail = toEmail;
    }

    @Size(max = 45)
    @Override
    public String getTitle() {
        return this.title;
    }

    @Override
    public void setTitle(String title) {
        this.title = title;
    }

    @Size(max = 65535)
    @Override
    public String getContent() {
        return this.content;
    }

    @Override
    public void setContent(String content) {
        this.content = content;
    }

    @Size(max = 255)
    @Override
    public String getRemark() {
        return this.remark;
    }

    @Override
    public void setRemark(String remark) {
        this.remark = remark;
    }

    @NotNull
    @Size(max = 40)
    @Override
    public String getEmailConfigId() {
        return this.emailConfigId;
    }

    @Override
    public void setEmailConfigId(String emailConfigId) {
        this.emailConfigId = emailConfigId;
    }

    @Override
    public Timestamp getCreateTime() {
        return this.createTime;
    }

    @Override
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CEmailSendPojo (");

        sb.append(id);
        sb.append(", ").append(fromEmail);
        sb.append(", ").append(toEmail);
        sb.append(", ").append(title);
        sb.append(", ").append(content);
        sb.append(", ").append(remark);
        sb.append(", ").append(emailConfigId);
        sb.append(", ").append(createTime);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ICEmailSend from) {
        setId(from.getId());
        setFromEmail(from.getFromEmail());
        setToEmail(from.getToEmail());
        setTitle(from.getTitle());
        setContent(from.getContent());
        setRemark(from.getRemark());
        setEmailConfigId(from.getEmailConfigId());
        setCreateTime(from.getCreateTime());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ICEmailSend> E into(E into) {
        into.from(this);
        return into;
    }
}
