/**
 * This class is generated by jOOQ
 */
package diamond.cms.server.model.jooq.tables.pojos;


import diamond.cms.server.model.jooq.tables.interfaces.ICPageView;

import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CPageViewPojo implements ICPageView {

    private static final long serialVersionUID = -969836153;

    private String    id;
    private String    name;
    private String    path;
    private String    params;
    private String    fullPath;
    private String    query;
    private Timestamp createTime;
    private String    ip;
    private String    userAgent;

    public CPageViewPojo() {}

    public CPageViewPojo(CPageViewPojo value) {
        this.id = value.id;
        this.name = value.name;
        this.path = value.path;
        this.params = value.params;
        this.fullPath = value.fullPath;
        this.query = value.query;
        this.createTime = value.createTime;
        this.ip = value.ip;
        this.userAgent = value.userAgent;
    }

    public CPageViewPojo(
        String    id,
        String    name,
        String    path,
        String    params,
        String    fullPath,
        String    query,
        Timestamp createTime,
        String    ip,
        String    userAgent
    ) {
        this.id = id;
        this.name = name;
        this.path = path;
        this.params = params;
        this.fullPath = fullPath;
        this.query = query;
        this.createTime = createTime;
        this.ip = ip;
        this.userAgent = userAgent;
    }

    @NotNull
    @Size(max = 40)
    @Override
    public String getId() {
        return this.id;
    }

    @Override
    public void setId(String id) {
        this.id = id;
    }

    @Size(max = 40)
    @Override
    public String getName() {
        return this.name;
    }

    @Override
    public void setName(String name) {
        this.name = name;
    }

    @Size(max = 255)
    @Override
    public String getPath() {
        return this.path;
    }

    @Override
    public void setPath(String path) {
        this.path = path;
    }

    @Size(max = 300)
    @Override
    public String getParams() {
        return this.params;
    }

    @Override
    public void setParams(String params) {
        this.params = params;
    }

    @Size(max = 300)
    @Override
    public String getFullPath() {
        return this.fullPath;
    }

    @Override
    public void setFullPath(String fullPath) {
        this.fullPath = fullPath;
    }

    @Size(max = 45)
    @Override
    public String getQuery() {
        return this.query;
    }

    @Override
    public void setQuery(String query) {
        this.query = query;
    }

    @Override
    public Timestamp getCreateTime() {
        return this.createTime;
    }

    @Override
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    @Size(max = 45)
    @Override
    public String getIp() {
        return this.ip;
    }

    @Override
    public void setIp(String ip) {
        this.ip = ip;
    }

    @Size(max = 300)
    @Override
    public String getUserAgent() {
        return this.userAgent;
    }

    @Override
    public void setUserAgent(String userAgent) {
        this.userAgent = userAgent;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CPageViewPojo (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(path);
        sb.append(", ").append(params);
        sb.append(", ").append(fullPath);
        sb.append(", ").append(query);
        sb.append(", ").append(createTime);
        sb.append(", ").append(ip);
        sb.append(", ").append(userAgent);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ICPageView from) {
        setId(from.getId());
        setName(from.getName());
        setPath(from.getPath());
        setParams(from.getParams());
        setFullPath(from.getFullPath());
        setQuery(from.getQuery());
        setCreateTime(from.getCreateTime());
        setIp(from.getIp());
        setUserAgent(from.getUserAgent());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ICPageView> E into(E into) {
        into.from(this);
        return into;
    }
}
