/**
 * This class is generated by jOOQ
 */
package diamond.cms.server.model.jooq.tables.pojos;


import diamond.cms.server.model.jooq.tables.interfaces.ICSetting;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CSettingPojo implements ICSetting {

	private static final long serialVersionUID = -1533670299;

	private String  id;
	private String  name;
	private String  value;
	private Integer type;
	private String  description;

	public CSettingPojo() {}

	public CSettingPojo(CSettingPojo value) {
		this.id = value.id;
		this.name = value.name;
		this.value = value.value;
		this.type = value.type;
		this.description = value.description;
	}

	public CSettingPojo(
		String  id,
		String  name,
		String  value,
		Integer type,
		String  description
	) {
		this.id = id;
		this.name = name;
		this.value = value;
		this.type = type;
		this.description = description;
	}

	@NotNull
	@Size(max = 120)
	@Override
	public String getId() {
		return this.id;
	}

	@Override
	public void setId(String id) {
		this.id = id;
	}

	@NotNull
	@Size(max = 45)
	@Override
	public String getName() {
		return this.name;
	}

	@Override
	public void setName(String name) {
		this.name = name;
	}

	@NotNull
	@Size(max = 65535)
	@Override
	public String getValue() {
		return this.value;
	}

	@Override
	public void setValue(String value) {
		this.value = value;
	}

	@NotNull
	@Override
	public Integer getType() {
		return this.type;
	}

	@Override
	public void setType(Integer type) {
		this.type = type;
	}

	@Size(max = 140)
	@Override
	public String getDescription() {
		return this.description;
	}

	@Override
	public void setDescription(String description) {
		this.description = description;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("CSettingPojo (");

		sb.append(id);
		sb.append(", ").append(name);
		sb.append(", ").append(value);
		sb.append(", ").append(type);
		sb.append(", ").append(description);

		sb.append(")");
		return sb.toString();
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(ICSetting from) {
		setId(from.getId());
		setName(from.getName());
		setValue(from.getValue());
		setType(from.getType());
		setDescription(from.getDescription());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends ICSetting> E into(E into) {
		into.from(this);
		return into;
	}
}
