/**
 * This class is generated by jOOQ
 */
package diamond.cms.server.model.jooq.tables.pojos;


import diamond.cms.server.model.jooq.tables.interfaces.ICUser;

import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CUserPojo implements ICUser {

	private static final long serialVersionUID = -1663451599;

	private String    id;
	private Timestamp createtime;
	private Long      expired;
	private Timestamp lastlogintime;
	private String    password;
	private String    token;
	private String    username;

	public CUserPojo() {}

	public CUserPojo(CUserPojo value) {
		this.id = value.id;
		this.createtime = value.createtime;
		this.expired = value.expired;
		this.lastlogintime = value.lastlogintime;
		this.password = value.password;
		this.token = value.token;
		this.username = value.username;
	}

	public CUserPojo(
		String    id,
		Timestamp createtime,
		Long      expired,
		Timestamp lastlogintime,
		String    password,
		String    token,
		String    username
	) {
		this.id = id;
		this.createtime = createtime;
		this.expired = expired;
		this.lastlogintime = lastlogintime;
		this.password = password;
		this.token = token;
		this.username = username;
	}

	@NotNull
	@Size(max = 255)
	@Override
	public String getId() {
		return this.id;
	}

	@Override
	public void setId(String id) {
		this.id = id;
	}

	@NotNull
	@Override
	public Timestamp getCreatetime() {
		return this.createtime;
	}

	@Override
	public void setCreatetime(Timestamp createtime) {
		this.createtime = createtime;
	}

	@Override
	public Long getExpired() {
		return this.expired;
	}

	@Override
	public void setExpired(Long expired) {
		this.expired = expired;
	}

	@NotNull
	@Override
	public Timestamp getLastlogintime() {
		return this.lastlogintime;
	}

	@Override
	public void setLastlogintime(Timestamp lastlogintime) {
		this.lastlogintime = lastlogintime;
	}

	@NotNull
	@Size(max = 255)
	@Override
	public String getPassword() {
		return this.password;
	}

	@Override
	public void setPassword(String password) {
		this.password = password;
	}

	@Size(max = 255)
	@Override
	public String getToken() {
		return this.token;
	}

	@Override
	public void setToken(String token) {
		this.token = token;
	}

	@NotNull
	@Size(max = 255)
	@Override
	public String getUsername() {
		return this.username;
	}

	@Override
	public void setUsername(String username) {
		this.username = username;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("CUserPojo (");

		sb.append(id);
		sb.append(", ").append(createtime);
		sb.append(", ").append(expired);
		sb.append(", ").append(lastlogintime);
		sb.append(", ").append(password);
		sb.append(", ").append(token);
		sb.append(", ").append(username);

		sb.append(")");
		return sb.toString();
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(ICUser from) {
		setId(from.getId());
		setCreatetime(from.getCreatetime());
		setExpired(from.getExpired());
		setLastlogintime(from.getLastlogintime());
		setPassword(from.getPassword());
		setToken(from.getToken());
		setUsername(from.getUsername());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends ICUser> E into(E into) {
		into.from(this);
		return into;
	}
}
