/**
 * This class is generated by jOOQ
 */
package diamond.cms.server.model.jooq.tables.pojos;


import diamond.cms.server.model.jooq.tables.interfaces.ICUser;

import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CUserPojo implements ICUser {

    private static final long serialVersionUID = -246480952;

    private String    id;
    private String    username;
    private String    password;
    private String    token;
    private Long      expired;
    private Timestamp createTime;
    private Timestamp lastLoginTime;

    public CUserPojo() {}

    public CUserPojo(CUserPojo value) {
        this.id = value.id;
        this.username = value.username;
        this.password = value.password;
        this.token = value.token;
        this.expired = value.expired;
        this.createTime = value.createTime;
        this.lastLoginTime = value.lastLoginTime;
    }

    public CUserPojo(
        String    id,
        String    username,
        String    password,
        String    token,
        Long      expired,
        Timestamp createTime,
        Timestamp lastLoginTime
    ) {
        this.id = id;
        this.username = username;
        this.password = password;
        this.token = token;
        this.expired = expired;
        this.createTime = createTime;
        this.lastLoginTime = lastLoginTime;
    }

    @NotNull
    @Size(max = 40)
    @Override
    public String getId() {
        return this.id;
    }

    @Override
    public void setId(String id) {
        this.id = id;
    }

    @NotNull
    @Size(max = 80)
    @Override
    public String getUsername() {
        return this.username;
    }

    @Override
    public void setUsername(String username) {
        this.username = username;
    }

    @NotNull
    @Size(max = 40)
    @Override
    public String getPassword() {
        return this.password;
    }

    @Override
    public void setPassword(String password) {
        this.password = password;
    }

    @Size(max = 80)
    @Override
    public String getToken() {
        return this.token;
    }

    @Override
    public void setToken(String token) {
        this.token = token;
    }

    @Override
    public Long getExpired() {
        return this.expired;
    }

    @Override
    public void setExpired(Long expired) {
        this.expired = expired;
    }

    @Override
    public Timestamp getCreateTime() {
        return this.createTime;
    }

    @Override
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    @Override
    public Timestamp getLastLoginTime() {
        return this.lastLoginTime;
    }

    @Override
    public void setLastLoginTime(Timestamp lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CUserPojo (");

        sb.append(id);
        sb.append(", ").append(username);
        sb.append(", ").append(password);
        sb.append(", ").append(token);
        sb.append(", ").append(expired);
        sb.append(", ").append(createTime);
        sb.append(", ").append(lastLoginTime);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ICUser from) {
        setId(from.getId());
        setUsername(from.getUsername());
        setPassword(from.getPassword());
        setToken(from.getToken());
        setExpired(from.getExpired());
        setCreateTime(from.getCreateTime());
        setLastLoginTime(from.getLastLoginTime());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ICUser> E into(E into) {
        into.from(this);
        return into;
    }
}
