/**
 * This class is generated by jOOQ
 */
package diamond.cms.server.model.jooq.tables;


import diamond.cms.server.model.jooq.Cms;
import diamond.cms.server.model.jooq.Keys;
import diamond.cms.server.model.jooq.tables.records.CCatalogRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CCatalog extends TableImpl<CCatalogRecord> {

	private static final long serialVersionUID = -1571131039;

	/**
	 * The reference instance of <code>cms.c_catalog</code>
	 */
	public static final CCatalog C_CATALOG = new CCatalog();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<CCatalogRecord> getRecordType() {
		return CCatalogRecord.class;
	}

	/**
	 * The column <code>cms.c_catalog.id</code>.
	 */
	public final TableField<CCatalogRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>cms.c_catalog.createTime</code>.
	 */
	public final TableField<CCatalogRecord, Timestamp> CREATETIME = createField("createTime", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>cms.c_catalog.name</code>.
	 */
	public final TableField<CCatalogRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>cms.c_catalog.updateTime</code>.
	 */
	public final TableField<CCatalogRecord, Timestamp> UPDATETIME = createField("updateTime", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>cms.c_catalog.parent_id</code>.
	 */
	public final TableField<CCatalogRecord, String> PARENT_ID = createField("parent_id", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * Create a <code>cms.c_catalog</code> table reference
	 */
	public CCatalog() {
		this("c_catalog", null);
	}

	/**
	 * Create an aliased <code>cms.c_catalog</code> table reference
	 */
	public CCatalog(String alias) {
		this(alias, C_CATALOG);
	}

	private CCatalog(String alias, Table<CCatalogRecord> aliased) {
		this(alias, aliased, null);
	}

	private CCatalog(String alias, Table<CCatalogRecord> aliased, Field<?>[] parameters) {
		super(alias, Cms.CMS, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<CCatalogRecord> getPrimaryKey() {
		return Keys.KEY_C_CATALOG_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<CCatalogRecord>> getKeys() {
		return Arrays.<UniqueKey<CCatalogRecord>>asList(Keys.KEY_C_CATALOG_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<CCatalogRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<CCatalogRecord, ?>>asList(Keys.FK_C6HY5PU5MCARTL5YWDWEHMXD3);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CCatalog as(String alias) {
		return new CCatalog(alias, this);
	}

	/**
	 * Rename this table
	 */
	public CCatalog rename(String name) {
		return new CCatalog(name, null);
	}
}
