/**
 * This class is generated by jOOQ
 */
package diamond.cms.server.model.jooq.tables;


import diamond.cms.server.model.jooq.Cms;
import diamond.cms.server.model.jooq.Keys;
import diamond.cms.server.model.jooq.tables.records.CGuestRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CGuest extends TableImpl<CGuestRecord> {

    private static final long serialVersionUID = 2021650673;

    /**
     * The reference instance of <code>cms.c_guest</code>
     */
    public static final CGuest C_GUEST = new CGuest();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CGuestRecord> getRecordType() {
        return CGuestRecord.class;
    }

    /**
     * The column <code>cms.c_guest.id</code>.
     */
    public final TableField<CGuestRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR.length(40).nullable(false), this, "");

    /**
     * The column <code>cms.c_guest.email</code>.
     */
    public final TableField<CGuestRecord, String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

    /**
     * The column <code>cms.c_guest.create_time</code>.
     */
    public final TableField<CGuestRecord, Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>cms.c_guest.login_time</code>.
     */
    public final TableField<CGuestRecord, Timestamp> LOGIN_TIME = createField("login_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>cms.c_guest.third_data</code>.
     */
    public final TableField<CGuestRecord, String> THIRD_DATA = createField("third_data", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>cms.c_guest.nickname</code>.
     */
    public final TableField<CGuestRecord, String> NICKNAME = createField("nickname", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>cms.c_guest.avatar</code>.
     */
    public final TableField<CGuestRecord, String> AVATAR = createField("avatar", org.jooq.impl.SQLDataType.VARCHAR.length(180), this, "");

    /**
     * Create a <code>cms.c_guest</code> table reference
     */
    public CGuest() {
        this("c_guest", null);
    }

    /**
     * Create an aliased <code>cms.c_guest</code> table reference
     */
    public CGuest(String alias) {
        this(alias, C_GUEST);
    }

    private CGuest(String alias, Table<CGuestRecord> aliased) {
        this(alias, aliased, null);
    }

    private CGuest(String alias, Table<CGuestRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Cms.CMS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CGuestRecord> getPrimaryKey() {
        return Keys.KEY_C_GUEST_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CGuestRecord>> getKeys() {
        return Arrays.<UniqueKey<CGuestRecord>>asList(Keys.KEY_C_GUEST_PRIMARY, Keys.KEY_C_GUEST_EMAIL_UNIQUE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CGuest as(String alias) {
        return new CGuest(alias, this);
    }

    /**
     * Rename this table
     */
    public CGuest rename(String name) {
        return new CGuest(name, null);
    }
}
