/**
 * This class is generated by jOOQ
 */
package diamond.cms.server.model.jooq.tables;


import diamond.cms.server.model.jooq.Cms;
import diamond.cms.server.model.jooq.Keys;
import diamond.cms.server.model.jooq.tables.records.CPageViewRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CPageView extends TableImpl<CPageViewRecord> {

    private static final long serialVersionUID = -966138218;

    /**
     * The reference instance of <code>cms.c_page_view</code>
     */
    public static final CPageView C_PAGE_VIEW = new CPageView();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CPageViewRecord> getRecordType() {
        return CPageViewRecord.class;
    }

    /**
     * The column <code>cms.c_page_view.id</code>.
     */
    public final TableField<CPageViewRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR.length(40).nullable(false), this, "");

    /**
     * The column <code>cms.c_page_view.name</code>.
     */
    public final TableField<CPageViewRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(40), this, "");

    /**
     * The column <code>cms.c_page_view.path</code>.
     */
    public final TableField<CPageViewRecord, String> PATH = createField("path", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>cms.c_page_view.params</code>.
     */
    public final TableField<CPageViewRecord, String> PARAMS = createField("params", org.jooq.impl.SQLDataType.VARCHAR.length(300), this, "");

    /**
     * The column <code>cms.c_page_view.full_path</code>.
     */
    public final TableField<CPageViewRecord, String> FULL_PATH = createField("full_path", org.jooq.impl.SQLDataType.VARCHAR.length(300), this, "");

    /**
     * The column <code>cms.c_page_view.query</code>.
     */
    public final TableField<CPageViewRecord, String> QUERY = createField("query", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

    /**
     * The column <code>cms.c_page_view.create_time</code>.
     */
    public final TableField<CPageViewRecord, Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>cms.c_page_view.ip</code>.
     */
    public final TableField<CPageViewRecord, String> IP = createField("ip", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

    /**
     * The column <code>cms.c_page_view.user_agent</code>.
     */
    public final TableField<CPageViewRecord, String> USER_AGENT = createField("user_agent", org.jooq.impl.SQLDataType.VARCHAR.length(300), this, "");

    /**
     * Create a <code>cms.c_page_view</code> table reference
     */
    public CPageView() {
        this("c_page_view", null);
    }

    /**
     * Create an aliased <code>cms.c_page_view</code> table reference
     */
    public CPageView(String alias) {
        this(alias, C_PAGE_VIEW);
    }

    private CPageView(String alias, Table<CPageViewRecord> aliased) {
        this(alias, aliased, null);
    }

    private CPageView(String alias, Table<CPageViewRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Cms.CMS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CPageViewRecord> getPrimaryKey() {
        return Keys.KEY_C_PAGE_VIEW_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CPageViewRecord>> getKeys() {
        return Arrays.<UniqueKey<CPageViewRecord>>asList(Keys.KEY_C_PAGE_VIEW_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CPageView as(String alias) {
        return new CPageView(alias, this);
    }

    /**
     * Rename this table
     */
    public CPageView rename(String name) {
        return new CPageView(name, null);
    }
}
