/**
 * This class is generated by jOOQ
 */
package diamond.cms.server.model.jooq.tables;


import diamond.cms.server.model.jooq.Cms;
import diamond.cms.server.model.jooq.Keys;
import diamond.cms.server.model.jooq.tables.records.CTagRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CTag extends TableImpl<CTagRecord> {

    private static final long serialVersionUID = 1695791397;

    /**
     * The reference instance of <code>cms.c_tag</code>
     */
    public static final CTag C_TAG = new CTag();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CTagRecord> getRecordType() {
        return CTagRecord.class;
    }

    /**
     * The column <code>cms.c_tag.id</code>.
     */
    public final TableField<CTagRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR.length(40).nullable(false), this, "");

    /**
     * The column <code>cms.c_tag.name</code>.
     */
    public final TableField<CTagRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

    /**
     * Create a <code>cms.c_tag</code> table reference
     */
    public CTag() {
        this("c_tag", null);
    }

    /**
     * Create an aliased <code>cms.c_tag</code> table reference
     */
    public CTag(String alias) {
        this(alias, C_TAG);
    }

    private CTag(String alias, Table<CTagRecord> aliased) {
        this(alias, aliased, null);
    }

    private CTag(String alias, Table<CTagRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Cms.CMS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CTagRecord> getPrimaryKey() {
        return Keys.KEY_C_TAG_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CTagRecord>> getKeys() {
        return Arrays.<UniqueKey<CTagRecord>>asList(Keys.KEY_C_TAG_PRIMARY, Keys.KEY_C_TAG_NAME_UNIQUE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CTag as(String alias) {
        return new CTag(alias, this);
    }

    /**
     * Rename this table
     */
    public CTag rename(String name) {
        return new CTag(name, null);
    }
}
