/**
 * This class is generated by jOOQ
 */
package diamond.cms.server.model.jooq.tables.interfaces;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ICArticle extends Serializable {

    /**
     * Setter for <code>cms.c_article.id</code>.
     */
    public void setId(String value);

    /**
     * Getter for <code>cms.c_article.id</code>.
     */
    @NotNull
    @Size(max = 40)
    public String getId();

    /**
     * Setter for <code>cms.c_article.title</code>.
     */
    public void setTitle(String value);

    /**
     * Getter for <code>cms.c_article.title</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getTitle();

    /**
     * Setter for <code>cms.c_article.content</code>.
     */
    public void setContent(String value);

    /**
     * Getter for <code>cms.c_article.content</code>.
     */
    @Size(max = 65535)
    public String getContent();

    /**
     * Setter for <code>cms.c_article.summary</code>. 文章摘要
     */
    public void setSummary(String value);

    /**
     * Getter for <code>cms.c_article.summary</code>. 文章摘要
     */
    @Size(max = 300)
    public String getSummary();

    /**
     * Setter for <code>cms.c_article.status</code>. 0: 删除状态
1: 草稿状态
2: 发布状态
     */
    public void setStatus(Integer value);

    /**
     * Getter for <code>cms.c_article.status</code>. 0: 删除状态
1: 草稿状态
2: 发布状态
     */
    public Integer getStatus();

    /**
     * Setter for <code>cms.c_article.create_time</code>.
     */
    public void setCreateTime(Timestamp value);

    /**
     * Getter for <code>cms.c_article.create_time</code>.
     */
    public Timestamp getCreateTime();

    /**
     * Setter for <code>cms.c_article.update_time</code>.
     */
    public void setUpdateTime(Timestamp value);

    /**
     * Getter for <code>cms.c_article.update_time</code>.
     */
    public Timestamp getUpdateTime();

    /**
     * Setter for <code>cms.c_article.catalog_id</code>.
     */
    public void setCatalogId(String value);

    /**
     * Getter for <code>cms.c_article.catalog_id</code>.
     */
    @Size(max = 40)
    public String getCatalogId();

    /**
     * Setter for <code>cms.c_article.banner</code>.
     */
    public void setBanner(String value);

    /**
     * Getter for <code>cms.c_article.banner</code>.
     */
    @Size(max = 150)
    public String getBanner();

    /**
     * Setter for <code>cms.c_article.tag_names</code>.
     */
    public void setTagNames(String value);

    /**
     * Getter for <code>cms.c_article.tag_names</code>.
     */
    @Size(max = 300)
    public String getTagNames();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ICArticle
     */
    public void from(diamond.cms.server.model.jooq.tables.interfaces.ICArticle from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ICArticle
     */
    public <E extends diamond.cms.server.model.jooq.tables.interfaces.ICArticle> E into(E into);
}
