/**
 * This class is generated by jOOQ
 */
package diamond.cms.server.model.jooq.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ICArticleTag extends Serializable {

    /**
     * Setter for <code>cms.c_article_tag.article_id</code>.
     */
    public void setArticleId(String value);

    /**
     * Getter for <code>cms.c_article_tag.article_id</code>.
     */
    @NotNull
    @Size(max = 40)
    public String getArticleId();

    /**
     * Setter for <code>cms.c_article_tag.tag_id</code>.
     */
    public void setTagId(String value);

    /**
     * Getter for <code>cms.c_article_tag.tag_id</code>.
     */
    @NotNull
    @Size(max = 40)
    public String getTagId();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ICArticleTag
     */
    public void from(diamond.cms.server.model.jooq.tables.interfaces.ICArticleTag from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ICArticleTag
     */
    public <E extends diamond.cms.server.model.jooq.tables.interfaces.ICArticleTag> E into(E into);
}
