/**
 * This class is generated by jOOQ
 */
package diamond.cms.server.model.jooq.tables.interfaces;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ICArticle extends Serializable {

	/**
	 * Setter for <code>cms.c_article.id</code>.
	 */
	public void setId(String value);

	/**
	 * Getter for <code>cms.c_article.id</code>.
	 */
	@NotNull
	@Size(max = 255)
	public String getId();

	/**
	 * Setter for <code>cms.c_article.content</code>.
	 */
	public void setContent(String value);

	/**
	 * Getter for <code>cms.c_article.content</code>.
	 */
	@NotNull
	@Size(max = 65535)
	public String getContent();

	/**
	 * Setter for <code>cms.c_article.createTime</code>.
	 */
	public void setCreatetime(Timestamp value);

	/**
	 * Getter for <code>cms.c_article.createTime</code>.
	 */
	@NotNull
	public Timestamp getCreatetime();

	/**
	 * Setter for <code>cms.c_article.title</code>.
	 */
	public void setTitle(String value);

	/**
	 * Getter for <code>cms.c_article.title</code>.
	 */
	@NotNull
	@Size(max = 255)
	public String getTitle();

	/**
	 * Setter for <code>cms.c_article.updateTime</code>.
	 */
	public void setUpdatetime(Timestamp value);

	/**
	 * Getter for <code>cms.c_article.updateTime</code>.
	 */
	@NotNull
	public Timestamp getUpdatetime();

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * Load data from another generated Record/POJO implementing the common interface ICArticle
	 */
	public void from(diamond.cms.server.model.jooq.tables.interfaces.ICArticle from);

	/**
	 * Copy data into another generated Record/POJO implementing the common interface ICArticle
	 */
	public <E extends diamond.cms.server.model.jooq.tables.interfaces.ICArticle> E into(E into);
}
