/**
 * This class is generated by jOOQ
 */
package diamond.cms.server.model.jooq.tables.interfaces;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ICCatalog extends Serializable {

	/**
	 * Setter for <code>cms.c_catalog.id</code>.
	 */
	public void setId(String value);

	/**
	 * Getter for <code>cms.c_catalog.id</code>.
	 */
	@NotNull
	@Size(max = 40)
	public String getId();

	/**
	 * Setter for <code>cms.c_catalog.name</code>.
	 */
	public void setName(String value);

	/**
	 * Getter for <code>cms.c_catalog.name</code>.
	 */
	@NotNull
	@Size(max = 30)
	public String getName();

	/**
	 * Setter for <code>cms.c_catalog.parent_id</code>.
	 */
	public void setParentId(String value);

	/**
	 * Getter for <code>cms.c_catalog.parent_id</code>.
	 */
	@Size(max = 40)
	public String getParentId();

	/**
	 * Setter for <code>cms.c_catalog.create_time</code>.
	 */
	public void setCreateTime(Timestamp value);

	/**
	 * Getter for <code>cms.c_catalog.create_time</code>.
	 */
	@NotNull
	public Timestamp getCreateTime();

	/**
	 * Setter for <code>cms.c_catalog.update_time</code>.
	 */
	public void setUpdateTime(Timestamp value);

	/**
	 * Getter for <code>cms.c_catalog.update_time</code>.
	 */
	@NotNull
	public Timestamp getUpdateTime();

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * Load data from another generated Record/POJO implementing the common interface ICCatalog
	 */
	public void from(diamond.cms.server.model.jooq.tables.interfaces.ICCatalog from);

	/**
	 * Copy data into another generated Record/POJO implementing the common interface ICCatalog
	 */
	public <E extends diamond.cms.server.model.jooq.tables.interfaces.ICCatalog> E into(E into);
}
