/**
 * This class is generated by jOOQ
 */
package diamond.cms.server.model.jooq.tables.interfaces;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ICEmailSend extends Serializable {

    /**
     * Setter for <code>cms.c_email_send.id</code>.
     */
    public void setId(String value);

    /**
     * Getter for <code>cms.c_email_send.id</code>.
     */
    @NotNull
    @Size(max = 40)
    public String getId();

    /**
     * Setter for <code>cms.c_email_send.from_email</code>.
     */
    public void setFromEmail(String value);

    /**
     * Getter for <code>cms.c_email_send.from_email</code>.
     */
    @NotNull
    @Size(max = 45)
    public String getFromEmail();

    /**
     * Setter for <code>cms.c_email_send.to_email</code>.
     */
    public void setToEmail(String value);

    /**
     * Getter for <code>cms.c_email_send.to_email</code>.
     */
    @NotNull
    @Size(max = 45)
    public String getToEmail();

    /**
     * Setter for <code>cms.c_email_send.title</code>.
     */
    public void setTitle(String value);

    /**
     * Getter for <code>cms.c_email_send.title</code>.
     */
    @Size(max = 45)
    public String getTitle();

    /**
     * Setter for <code>cms.c_email_send.content</code>.
     */
    public void setContent(String value);

    /**
     * Getter for <code>cms.c_email_send.content</code>.
     */
    @Size(max = 65535)
    public String getContent();

    /**
     * Setter for <code>cms.c_email_send.remark</code>.
     */
    public void setRemark(String value);

    /**
     * Getter for <code>cms.c_email_send.remark</code>.
     */
    @Size(max = 255)
    public String getRemark();

    /**
     * Setter for <code>cms.c_email_send.email_config_id</code>.
     */
    public void setEmailConfigId(String value);

    /**
     * Getter for <code>cms.c_email_send.email_config_id</code>.
     */
    @NotNull
    @Size(max = 40)
    public String getEmailConfigId();

    /**
     * Setter for <code>cms.c_email_send.create_time</code>.
     */
    public void setCreateTime(Timestamp value);

    /**
     * Getter for <code>cms.c_email_send.create_time</code>.
     */
    public Timestamp getCreateTime();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ICEmailSend
     */
    public void from(diamond.cms.server.model.jooq.tables.interfaces.ICEmailSend from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ICEmailSend
     */
    public <E extends diamond.cms.server.model.jooq.tables.interfaces.ICEmailSend> E into(E into);
}
