/**
 * This class is generated by jOOQ
 */
package diamond.cms.server.model.jooq.tables.interfaces;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ICGuest extends Serializable {

    /**
     * Setter for <code>cms.c_guest.id</code>.
     */
    public void setId(String value);

    /**
     * Getter for <code>cms.c_guest.id</code>.
     */
    @NotNull
    @Size(max = 40)
    public String getId();

    /**
     * Setter for <code>cms.c_guest.email</code>.
     */
    public void setEmail(String value);

    /**
     * Getter for <code>cms.c_guest.email</code>.
     */
    @NotNull
    @Size(max = 100)
    public String getEmail();

    /**
     * Setter for <code>cms.c_guest.create_time</code>.
     */
    public void setCreateTime(Timestamp value);

    /**
     * Getter for <code>cms.c_guest.create_time</code>.
     */
    public Timestamp getCreateTime();

    /**
     * Setter for <code>cms.c_guest.login_time</code>.
     */
    public void setLoginTime(Timestamp value);

    /**
     * Getter for <code>cms.c_guest.login_time</code>.
     */
    public Timestamp getLoginTime();

    /**
     * Setter for <code>cms.c_guest.third_data</code>.
     */
    public void setThirdData(String value);

    /**
     * Getter for <code>cms.c_guest.third_data</code>.
     */
    @Size(max = 65535)
    public String getThirdData();

    /**
     * Setter for <code>cms.c_guest.nickname</code>.
     */
    public void setNickname(String value);

    /**
     * Getter for <code>cms.c_guest.nickname</code>.
     */
    @Size(max = 255)
    public String getNickname();

    /**
     * Setter for <code>cms.c_guest.avatar</code>.
     */
    public void setAvatar(String value);

    /**
     * Getter for <code>cms.c_guest.avatar</code>.
     */
    @Size(max = 180)
    public String getAvatar();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ICGuest
     */
    public void from(diamond.cms.server.model.jooq.tables.interfaces.ICGuest from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ICGuest
     */
    public <E extends diamond.cms.server.model.jooq.tables.interfaces.ICGuest> E into(E into);
}
