/**
 * This class is generated by jOOQ
 */
package diamond.cms.server.model.jooq.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ICIpLocation extends Serializable {

    /**
     * Setter for <code>cms.c_ip_location.ip</code>.
     */
    public void setIp(String value);

    /**
     * Getter for <code>cms.c_ip_location.ip</code>.
     */
    @NotNull
    @Size(max = 20)
    public String getIp();

    /**
     * Setter for <code>cms.c_ip_location.location</code>.
     */
    public void setLocation(String value);

    /**
     * Getter for <code>cms.c_ip_location.location</code>.
     */
    @Size(max = 45)
    public String getLocation();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ICIpLocation
     */
    public void from(diamond.cms.server.model.jooq.tables.interfaces.ICIpLocation from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ICIpLocation
     */
    public <E extends diamond.cms.server.model.jooq.tables.interfaces.ICIpLocation> E into(E into);
}
