/**
 * This class is generated by jOOQ
 */
package diamond.cms.server.model.jooq.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ICKeyword extends Serializable {

    /**
     * Setter for <code>cms.c_keyword.id</code>.
     */
    public void setId(String value);

    /**
     * Getter for <code>cms.c_keyword.id</code>.
     */
    @NotNull
    @Size(max = 40)
    public String getId();

    /**
     * Setter for <code>cms.c_keyword.keyword</code>.
     */
    public void setKeyword(String value);

    /**
     * Getter for <code>cms.c_keyword.keyword</code>.
     */
    @NotNull
    @Size(max = 80)
    public String getKeyword();

    /**
     * Setter for <code>cms.c_keyword.ref_number</code>.
     */
    public void setRefNumber(Integer value);

    /**
     * Getter for <code>cms.c_keyword.ref_number</code>.
     */
    public Integer getRefNumber();

    /**
     * Setter for <code>cms.c_keyword.full_pinyin</code>.
     */
    public void setFullPinyin(String value);

    /**
     * Getter for <code>cms.c_keyword.full_pinyin</code>.
     */
    @NotNull
    @Size(max = 300)
    public String getFullPinyin();

    /**
     * Setter for <code>cms.c_keyword.simple_pinyin</code>.
     */
    public void setSimplePinyin(String value);

    /**
     * Getter for <code>cms.c_keyword.simple_pinyin</code>.
     */
    @NotNull
    @Size(max = 80)
    public String getSimplePinyin();

    /**
     * Setter for <code>cms.c_keyword.heat_number</code>.
     */
    public void setHeatNumber(Integer value);

    /**
     * Getter for <code>cms.c_keyword.heat_number</code>.
     */
    public Integer getHeatNumber();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ICKeyword
     */
    public void from(diamond.cms.server.model.jooq.tables.interfaces.ICKeyword from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ICKeyword
     */
    public <E extends diamond.cms.server.model.jooq.tables.interfaces.ICKeyword> E into(E into);
}
