/**
 * This class is generated by jOOQ
 */
package diamond.cms.server.model.jooq.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ICSetting extends Serializable {

    /**
     * Setter for <code>cms.c_setting.id</code>.
     */
    public void setId(String value);

    /**
     * Getter for <code>cms.c_setting.id</code>.
     */
    @NotNull
    @Size(max = 120)
    public String getId();

    /**
     * Setter for <code>cms.c_setting.name</code>. 参数key
     */
    public void setName(String value);

    /**
     * Getter for <code>cms.c_setting.name</code>. 参数key
     */
    @NotNull
    @Size(max = 45)
    public String getName();

    /**
     * Setter for <code>cms.c_setting.value</code>.
     */
    public void setValue(String value);

    /**
     * Getter for <code>cms.c_setting.value</code>.
     */
    @NotNull
    @Size(max = 65535)
    public String getValue();

    /**
     * Setter for <code>cms.c_setting.type</code>. 1: 普通文本
     */
    public void setType(Integer value);

    /**
     * Getter for <code>cms.c_setting.type</code>. 1: 普通文本
     */
    public Integer getType();

    /**
     * Setter for <code>cms.c_setting.description</code>. 备注
     */
    public void setDescription(String value);

    /**
     * Getter for <code>cms.c_setting.description</code>. 备注
     */
    @Size(max = 140)
    public String getDescription();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ICSetting
     */
    public void from(diamond.cms.server.model.jooq.tables.interfaces.ICSetting from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ICSetting
     */
    public <E extends diamond.cms.server.model.jooq.tables.interfaces.ICSetting> E into(E into);
}
