/**
 * This class is generated by jOOQ
 */
package diamond.cms.server.model.jooq.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ICTag extends Serializable {

	/**
	 * Setter for <code>cms.c_tag.id</code>.
	 */
	public void setId(String value);

	/**
	 * Getter for <code>cms.c_tag.id</code>.
	 */
	@NotNull
	@Size(max = 40)
	public String getId();

	/**
	 * Setter for <code>cms.c_tag.name</code>.
	 */
	public void setName(String value);

	/**
	 * Getter for <code>cms.c_tag.name</code>.
	 */
	@NotNull
	@Size(max = 45)
	public String getName();

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * Load data from another generated Record/POJO implementing the common interface ICTag
	 */
	public void from(diamond.cms.server.model.jooq.tables.interfaces.ICTag from);

	/**
	 * Copy data into another generated Record/POJO implementing the common interface ICTag
	 */
	public <E extends diamond.cms.server.model.jooq.tables.interfaces.ICTag> E into(E into);
}
