/**
 * This class is generated by jOOQ
 */
package diamond.cms.server.model.jooq.tables.records;


import diamond.cms.server.model.jooq.tables.CArticleTag;
import diamond.cms.server.model.jooq.tables.interfaces.ICArticleTag;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CArticleTagRecord extends UpdatableRecordImpl<CArticleTagRecord> implements Record2<String, String>, ICArticleTag {

    private static final long serialVersionUID = -1177874486;

    /**
     * Setter for <code>cms.c_article_tag.article_id</code>.
     */
    @Override
    public void setArticleId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>cms.c_article_tag.article_id</code>.
     */
    @NotNull
    @Size(max = 40)
    @Override
    public String getArticleId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>cms.c_article_tag.tag_id</code>.
     */
    @Override
    public void setTagId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>cms.c_article_tag.tag_id</code>.
     */
    @NotNull
    @Size(max = 40)
    @Override
    public String getTagId() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return CArticleTag.C_ARTICLE_TAG.ARTICLE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return CArticleTag.C_ARTICLE_TAG.TAG_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getArticleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTagId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CArticleTagRecord value1(String value) {
        setArticleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CArticleTagRecord value2(String value) {
        setTagId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CArticleTagRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ICArticleTag from) {
        setArticleId(from.getArticleId());
        setTagId(from.getTagId());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ICArticleTag> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CArticleTagRecord
     */
    public CArticleTagRecord() {
        super(CArticleTag.C_ARTICLE_TAG);
    }

    /**
     * Create a detached, initialised CArticleTagRecord
     */
    public CArticleTagRecord(String articleId, String tagId) {
        super(CArticleTag.C_ARTICLE_TAG);

        set(0, articleId);
        set(1, tagId);
    }
}
