/**
 * This class is generated by jOOQ
 */
package diamond.cms.server.model.jooq.tables.records;


import diamond.cms.server.model.jooq.tables.CArticle;
import diamond.cms.server.model.jooq.tables.interfaces.ICArticle;

import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CArticleRecord extends UpdatableRecordImpl<CArticleRecord> implements Record5<String, String, Timestamp, String, Timestamp>, ICArticle {

	private static final long serialVersionUID = -1494770431;

	/**
	 * Setter for <code>cms.c_article.id</code>.
	 */
	@Override
	public void setId(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>cms.c_article.id</code>.
	 */
	@NotNull
	@Size(max = 255)
	@Override
	public String getId() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>cms.c_article.content</code>.
	 */
	@Override
	public void setContent(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>cms.c_article.content</code>.
	 */
	@NotNull
	@Size(max = 65535)
	@Override
	public String getContent() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>cms.c_article.createTime</code>.
	 */
	@Override
	public void setCreatetime(Timestamp value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>cms.c_article.createTime</code>.
	 */
	@NotNull
	@Override
	public Timestamp getCreatetime() {
		return (Timestamp) getValue(2);
	}

	/**
	 * Setter for <code>cms.c_article.title</code>.
	 */
	@Override
	public void setTitle(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>cms.c_article.title</code>.
	 */
	@NotNull
	@Size(max = 255)
	@Override
	public String getTitle() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>cms.c_article.updateTime</code>.
	 */
	@Override
	public void setUpdatetime(Timestamp value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>cms.c_article.updateTime</code>.
	 */
	@NotNull
	@Override
	public Timestamp getUpdatetime() {
		return (Timestamp) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<String, String, Timestamp, String, Timestamp> fieldsRow() {
		return (Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<String, String, Timestamp, String, Timestamp> valuesRow() {
		return (Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return CArticle.C_ARTICLE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return CArticle.C_ARTICLE.CONTENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field3() {
		return CArticle.C_ARTICLE.CREATETIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return CArticle.C_ARTICLE.TITLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field5() {
		return CArticle.C_ARTICLE.UPDATETIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getContent();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value3() {
		return getCreatetime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getTitle();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value5() {
		return getUpdatetime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CArticleRecord value1(String value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CArticleRecord value2(String value) {
		setContent(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CArticleRecord value3(Timestamp value) {
		setCreatetime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CArticleRecord value4(String value) {
		setTitle(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CArticleRecord value5(Timestamp value) {
		setUpdatetime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CArticleRecord values(String value1, String value2, Timestamp value3, String value4, Timestamp value5) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		return this;
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(ICArticle from) {
		setId(from.getId());
		setContent(from.getContent());
		setCreatetime(from.getCreatetime());
		setTitle(from.getTitle());
		setUpdatetime(from.getUpdatetime());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends ICArticle> E into(E into) {
		into.from(this);
		return into;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CArticleRecord
	 */
	public CArticleRecord() {
		super(CArticle.C_ARTICLE);
	}

	/**
	 * Create a detached, initialised CArticleRecord
	 */
	public CArticleRecord(String id, String content, Timestamp createtime, String title, Timestamp updatetime) {
		super(CArticle.C_ARTICLE);

		setValue(0, id);
		setValue(1, content);
		setValue(2, createtime);
		setValue(3, title);
		setValue(4, updatetime);
	}
}
