/**
 * This class is generated by jOOQ
 */
package diamond.cms.server.model.jooq.tables.records;


import diamond.cms.server.model.jooq.tables.CCatalog;
import diamond.cms.server.model.jooq.tables.interfaces.ICCatalog;

import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CCatalogRecord extends UpdatableRecordImpl<CCatalogRecord> implements Record5<String, Timestamp, String, Timestamp, String>, ICCatalog {

	private static final long serialVersionUID = 752377935;

	/**
	 * Setter for <code>cms.c_catalog.id</code>.
	 */
	@Override
	public void setId(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>cms.c_catalog.id</code>.
	 */
	@NotNull
	@Size(max = 255)
	@Override
	public String getId() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>cms.c_catalog.createTime</code>.
	 */
	@Override
	public void setCreatetime(Timestamp value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>cms.c_catalog.createTime</code>.
	 */
	@NotNull
	@Override
	public Timestamp getCreatetime() {
		return (Timestamp) getValue(1);
	}

	/**
	 * Setter for <code>cms.c_catalog.name</code>.
	 */
	@Override
	public void setName(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>cms.c_catalog.name</code>.
	 */
	@NotNull
	@Size(max = 255)
	@Override
	public String getName() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>cms.c_catalog.updateTime</code>.
	 */
	@Override
	public void setUpdatetime(Timestamp value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>cms.c_catalog.updateTime</code>.
	 */
	@NotNull
	@Override
	public Timestamp getUpdatetime() {
		return (Timestamp) getValue(3);
	}

	/**
	 * Setter for <code>cms.c_catalog.parent_id</code>.
	 */
	@Override
	public void setParentId(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>cms.c_catalog.parent_id</code>.
	 */
	@Size(max = 255)
	@Override
	public String getParentId() {
		return (String) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<String, Timestamp, String, Timestamp, String> fieldsRow() {
		return (Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<String, Timestamp, String, Timestamp, String> valuesRow() {
		return (Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return CCatalog.C_CATALOG.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field2() {
		return CCatalog.C_CATALOG.CREATETIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return CCatalog.C_CATALOG.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field4() {
		return CCatalog.C_CATALOG.UPDATETIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return CCatalog.C_CATALOG.PARENT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value2() {
		return getCreatetime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value4() {
		return getUpdatetime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getParentId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CCatalogRecord value1(String value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CCatalogRecord value2(Timestamp value) {
		setCreatetime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CCatalogRecord value3(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CCatalogRecord value4(Timestamp value) {
		setUpdatetime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CCatalogRecord value5(String value) {
		setParentId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CCatalogRecord values(String value1, Timestamp value2, String value3, Timestamp value4, String value5) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		return this;
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(ICCatalog from) {
		setId(from.getId());
		setCreatetime(from.getCreatetime());
		setName(from.getName());
		setUpdatetime(from.getUpdatetime());
		setParentId(from.getParentId());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends ICCatalog> E into(E into) {
		into.from(this);
		return into;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CCatalogRecord
	 */
	public CCatalogRecord() {
		super(CCatalog.C_CATALOG);
	}

	/**
	 * Create a detached, initialised CCatalogRecord
	 */
	public CCatalogRecord(String id, Timestamp createtime, String name, Timestamp updatetime, String parentId) {
		super(CCatalog.C_CATALOG);

		setValue(0, id);
		setValue(1, createtime);
		setValue(2, name);
		setValue(3, updatetime);
		setValue(4, parentId);
	}
}
