/**
 * This class is generated by jOOQ
 */
package diamond.cms.server.model.jooq.tables.records;


import diamond.cms.server.model.jooq.tables.CEmailSend;
import diamond.cms.server.model.jooq.tables.interfaces.ICEmailSend;

import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CEmailSendRecord extends UpdatableRecordImpl<CEmailSendRecord> implements Record8<String, String, String, String, String, String, String, Timestamp>, ICEmailSend {

    private static final long serialVersionUID = 2066066764;

    /**
     * Setter for <code>cms.c_email_send.id</code>.
     */
    @Override
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>cms.c_email_send.id</code>.
     */
    @NotNull
    @Size(max = 40)
    @Override
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>cms.c_email_send.from_email</code>.
     */
    @Override
    public void setFromEmail(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>cms.c_email_send.from_email</code>.
     */
    @NotNull
    @Size(max = 45)
    @Override
    public String getFromEmail() {
        return (String) get(1);
    }

    /**
     * Setter for <code>cms.c_email_send.to_email</code>.
     */
    @Override
    public void setToEmail(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>cms.c_email_send.to_email</code>.
     */
    @NotNull
    @Size(max = 45)
    @Override
    public String getToEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>cms.c_email_send.title</code>.
     */
    @Override
    public void setTitle(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>cms.c_email_send.title</code>.
     */
    @Size(max = 45)
    @Override
    public String getTitle() {
        return (String) get(3);
    }

    /**
     * Setter for <code>cms.c_email_send.content</code>.
     */
    @Override
    public void setContent(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>cms.c_email_send.content</code>.
     */
    @Size(max = 65535)
    @Override
    public String getContent() {
        return (String) get(4);
    }

    /**
     * Setter for <code>cms.c_email_send.remark</code>.
     */
    @Override
    public void setRemark(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>cms.c_email_send.remark</code>.
     */
    @Size(max = 255)
    @Override
    public String getRemark() {
        return (String) get(5);
    }

    /**
     * Setter for <code>cms.c_email_send.email_config_id</code>.
     */
    @Override
    public void setEmailConfigId(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>cms.c_email_send.email_config_id</code>.
     */
    @NotNull
    @Size(max = 40)
    @Override
    public String getEmailConfigId() {
        return (String) get(6);
    }

    /**
     * Setter for <code>cms.c_email_send.create_time</code>.
     */
    @Override
    public void setCreateTime(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>cms.c_email_send.create_time</code>.
     */
    @Override
    public Timestamp getCreateTime() {
        return (Timestamp) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<String, String, String, String, String, String, String, Timestamp> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<String, String, String, String, String, String, String, Timestamp> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return CEmailSend.C_EMAIL_SEND.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return CEmailSend.C_EMAIL_SEND.FROM_EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return CEmailSend.C_EMAIL_SEND.TO_EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return CEmailSend.C_EMAIL_SEND.TITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return CEmailSend.C_EMAIL_SEND.CONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return CEmailSend.C_EMAIL_SEND.REMARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return CEmailSend.C_EMAIL_SEND.EMAIL_CONFIG_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return CEmailSend.C_EMAIL_SEND.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getFromEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getToEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getEmailConfigId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CEmailSendRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CEmailSendRecord value2(String value) {
        setFromEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CEmailSendRecord value3(String value) {
        setToEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CEmailSendRecord value4(String value) {
        setTitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CEmailSendRecord value5(String value) {
        setContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CEmailSendRecord value6(String value) {
        setRemark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CEmailSendRecord value7(String value) {
        setEmailConfigId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CEmailSendRecord value8(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CEmailSendRecord values(String value1, String value2, String value3, String value4, String value5, String value6, String value7, Timestamp value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ICEmailSend from) {
        setId(from.getId());
        setFromEmail(from.getFromEmail());
        setToEmail(from.getToEmail());
        setTitle(from.getTitle());
        setContent(from.getContent());
        setRemark(from.getRemark());
        setEmailConfigId(from.getEmailConfigId());
        setCreateTime(from.getCreateTime());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ICEmailSend> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CEmailSendRecord
     */
    public CEmailSendRecord() {
        super(CEmailSend.C_EMAIL_SEND);
    }

    /**
     * Create a detached, initialised CEmailSendRecord
     */
    public CEmailSendRecord(String id, String fromEmail, String toEmail, String title, String content, String remark, String emailConfigId, Timestamp createTime) {
        super(CEmailSend.C_EMAIL_SEND);

        set(0, id);
        set(1, fromEmail);
        set(2, toEmail);
        set(3, title);
        set(4, content);
        set(5, remark);
        set(6, emailConfigId);
        set(7, createTime);
    }
}
