/**
 * This class is generated by jOOQ
 */
package diamond.cms.server.model.jooq.tables.records;


import diamond.cms.server.model.jooq.tables.CEmailConfig;
import diamond.cms.server.model.jooq.tables.interfaces.ICEmailConfig;

import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CEmailConfigRecord extends UpdatableRecordImpl<CEmailConfigRecord> implements Record8<String, String, Integer, Boolean, String, String, Boolean, Timestamp>, ICEmailConfig {

    private static final long serialVersionUID = 1561324823;

    /**
     * Setter for <code>cms.c_email_config.id</code>.
     */
    @Override
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>cms.c_email_config.id</code>.
     */
    @NotNull
    @Size(max = 40)
    @Override
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>cms.c_email_config.smtp_host</code>.
     */
    @Override
    public void setSmtpHost(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>cms.c_email_config.smtp_host</code>.
     */
    @NotNull
    @Size(max = 45)
    @Override
    public String getSmtpHost() {
        return (String) get(1);
    }

    /**
     * Setter for <code>cms.c_email_config.smtp_port</code>.
     */
    @Override
    public void setSmtpPort(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>cms.c_email_config.smtp_port</code>.
     */
    @NotNull
    @Override
    public Integer getSmtpPort() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>cms.c_email_config.ssl_enable</code>. 1: 启用
0: 禁用
     */
    @Override
    public void setSslEnable(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>cms.c_email_config.ssl_enable</code>. 1: 启用
0: 禁用
     */
    @Override
    public Boolean getSslEnable() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>cms.c_email_config.email_account</code>.
     */
    @Override
    public void setEmailAccount(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>cms.c_email_config.email_account</code>.
     */
    @NotNull
    @Size(max = 60)
    @Override
    public String getEmailAccount() {
        return (String) get(4);
    }

    /**
     * Setter for <code>cms.c_email_config.email_password</code>.
     */
    @Override
    public void setEmailPassword(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>cms.c_email_config.email_password</code>.
     */
    @NotNull
    @Size(max = 60)
    @Override
    public String getEmailPassword() {
        return (String) get(5);
    }

    /**
     * Setter for <code>cms.c_email_config.enable</code>. 0: 禁用
1: 启用
是否启用配置
     */
    @Override
    public void setEnable(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>cms.c_email_config.enable</code>. 0: 禁用
1: 启用
是否启用配置
     */
    @Override
    public Boolean getEnable() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>cms.c_email_config.create_time</code>.
     */
    @Override
    public void setCreateTime(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>cms.c_email_config.create_time</code>.
     */
    @Override
    public Timestamp getCreateTime() {
        return (Timestamp) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<String, String, Integer, Boolean, String, String, Boolean, Timestamp> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<String, String, Integer, Boolean, String, String, Boolean, Timestamp> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return CEmailConfig.C_EMAIL_CONFIG.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return CEmailConfig.C_EMAIL_CONFIG.SMTP_HOST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return CEmailConfig.C_EMAIL_CONFIG.SMTP_PORT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field4() {
        return CEmailConfig.C_EMAIL_CONFIG.SSL_ENABLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return CEmailConfig.C_EMAIL_CONFIG.EMAIL_ACCOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return CEmailConfig.C_EMAIL_CONFIG.EMAIL_PASSWORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field7() {
        return CEmailConfig.C_EMAIL_CONFIG.ENABLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return CEmailConfig.C_EMAIL_CONFIG.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getSmtpHost();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getSmtpPort();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value4() {
        return getSslEnable();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getEmailAccount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getEmailPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value7() {
        return getEnable();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CEmailConfigRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CEmailConfigRecord value2(String value) {
        setSmtpHost(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CEmailConfigRecord value3(Integer value) {
        setSmtpPort(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CEmailConfigRecord value4(Boolean value) {
        setSslEnable(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CEmailConfigRecord value5(String value) {
        setEmailAccount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CEmailConfigRecord value6(String value) {
        setEmailPassword(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CEmailConfigRecord value7(Boolean value) {
        setEnable(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CEmailConfigRecord value8(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CEmailConfigRecord values(String value1, String value2, Integer value3, Boolean value4, String value5, String value6, Boolean value7, Timestamp value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ICEmailConfig from) {
        setId(from.getId());
        setSmtpHost(from.getSmtpHost());
        setSmtpPort(from.getSmtpPort());
        setSslEnable(from.getSslEnable());
        setEmailAccount(from.getEmailAccount());
        setEmailPassword(from.getEmailPassword());
        setEnable(from.getEnable());
        setCreateTime(from.getCreateTime());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ICEmailConfig> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CEmailConfigRecord
     */
    public CEmailConfigRecord() {
        super(CEmailConfig.C_EMAIL_CONFIG);
    }

    /**
     * Create a detached, initialised CEmailConfigRecord
     */
    public CEmailConfigRecord(String id, String smtpHost, Integer smtpPort, Boolean sslEnable, String emailAccount, String emailPassword, Boolean enable, Timestamp createTime) {
        super(CEmailConfig.C_EMAIL_CONFIG);

        set(0, id);
        set(1, smtpHost);
        set(2, smtpPort);
        set(3, sslEnable);
        set(4, emailAccount);
        set(5, emailPassword);
        set(6, enable);
        set(7, createTime);
    }
}
