/**
 * This class is generated by jOOQ
 */
package diamond.cms.server.model.jooq.tables.records;


import diamond.cms.server.model.jooq.tables.CPageView;
import diamond.cms.server.model.jooq.tables.interfaces.ICPageView;

import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CPageViewRecord extends UpdatableRecordImpl<CPageViewRecord> implements Record8<String, String, String, String, String, String, Timestamp, String>, ICPageView {

	private static final long serialVersionUID = 2046641984;

	/**
	 * Setter for <code>cms.c_page_view.id</code>.
	 */
	@Override
	public void setId(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>cms.c_page_view.id</code>.
	 */
	@NotNull
	@Size(max = 40)
	@Override
	public String getId() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>cms.c_page_view.name</code>.
	 */
	@Override
	public void setName(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>cms.c_page_view.name</code>.
	 */
	@Size(max = 40)
	@Override
	public String getName() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>cms.c_page_view.path</code>.
	 */
	@Override
	public void setPath(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>cms.c_page_view.path</code>.
	 */
	@Size(max = 255)
	@Override
	public String getPath() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>cms.c_page_view.params</code>.
	 */
	@Override
	public void setParams(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>cms.c_page_view.params</code>.
	 */
	@Size(max = 300)
	@Override
	public String getParams() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>cms.c_page_view.full_path</code>.
	 */
	@Override
	public void setFullPath(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>cms.c_page_view.full_path</code>.
	 */
	@Size(max = 300)
	@Override
	public String getFullPath() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>cms.c_page_view.query</code>.
	 */
	@Override
	public void setQuery(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>cms.c_page_view.query</code>.
	 */
	@Size(max = 45)
	@Override
	public String getQuery() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>cms.c_page_view.create_time</code>.
	 */
	@Override
	public void setCreateTime(Timestamp value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>cms.c_page_view.create_time</code>.
	 */
	@NotNull
	@Override
	public Timestamp getCreateTime() {
		return (Timestamp) getValue(6);
	}

	/**
	 * Setter for <code>cms.c_page_view.ip</code>.
	 */
	@Override
	public void setIp(String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>cms.c_page_view.ip</code>.
	 */
	@Size(max = 45)
	@Override
	public String getIp() {
		return (String) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<String, String, String, String, String, String, Timestamp, String> fieldsRow() {
		return (Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<String, String, String, String, String, String, Timestamp, String> valuesRow() {
		return (Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return CPageView.C_PAGE_VIEW.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return CPageView.C_PAGE_VIEW.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return CPageView.C_PAGE_VIEW.PATH;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return CPageView.C_PAGE_VIEW.PARAMS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return CPageView.C_PAGE_VIEW.FULL_PATH;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return CPageView.C_PAGE_VIEW.QUERY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field7() {
		return CPageView.C_PAGE_VIEW.CREATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field8() {
		return CPageView.C_PAGE_VIEW.IP;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getPath();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getParams();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getFullPath();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getQuery();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value7() {
		return getCreateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value8() {
		return getIp();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CPageViewRecord value1(String value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CPageViewRecord value2(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CPageViewRecord value3(String value) {
		setPath(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CPageViewRecord value4(String value) {
		setParams(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CPageViewRecord value5(String value) {
		setFullPath(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CPageViewRecord value6(String value) {
		setQuery(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CPageViewRecord value7(Timestamp value) {
		setCreateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CPageViewRecord value8(String value) {
		setIp(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CPageViewRecord values(String value1, String value2, String value3, String value4, String value5, String value6, Timestamp value7, String value8) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		return this;
	}

	// -------------------------------------------------------------------------
	// FROM and INTO
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void from(ICPageView from) {
		setId(from.getId());
		setName(from.getName());
		setPath(from.getPath());
		setParams(from.getParams());
		setFullPath(from.getFullPath());
		setQuery(from.getQuery());
		setCreateTime(from.getCreateTime());
		setIp(from.getIp());
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public <E extends ICPageView> E into(E into) {
		into.from(this);
		return into;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CPageViewRecord
	 */
	public CPageViewRecord() {
		super(CPageView.C_PAGE_VIEW);
	}

	/**
	 * Create a detached, initialised CPageViewRecord
	 */
	public CPageViewRecord(String id, String name, String path, String params, String fullPath, String query, Timestamp createTime, String ip) {
		super(CPageView.C_PAGE_VIEW);

		setValue(0, id);
		setValue(1, name);
		setValue(2, path);
		setValue(3, params);
		setValue(4, fullPath);
		setValue(5, query);
		setValue(6, createTime);
		setValue(7, ip);
	}
}
