/**
 * This class is generated by jOOQ
 */
package diamond.cms.server.model.jooq.tables.records;


import diamond.cms.server.model.jooq.tables.CUser;
import diamond.cms.server.model.jooq.tables.interfaces.ICUser;

import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CUserRecord extends UpdatableRecordImpl<CUserRecord> implements Record7<String, String, String, String, Long, Timestamp, Timestamp>, ICUser {

    private static final long serialVersionUID = 19376846;

    /**
     * Setter for <code>cms.c_user.id</code>.
     */
    @Override
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>cms.c_user.id</code>.
     */
    @NotNull
    @Size(max = 40)
    @Override
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>cms.c_user.username</code>.
     */
    @Override
    public void setUsername(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>cms.c_user.username</code>.
     */
    @NotNull
    @Size(max = 80)
    @Override
    public String getUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>cms.c_user.password</code>.
     */
    @Override
    public void setPassword(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>cms.c_user.password</code>.
     */
    @NotNull
    @Size(max = 40)
    @Override
    public String getPassword() {
        return (String) get(2);
    }

    /**
     * Setter for <code>cms.c_user.token</code>.
     */
    @Override
    public void setToken(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>cms.c_user.token</code>.
     */
    @Size(max = 80)
    @Override
    public String getToken() {
        return (String) get(3);
    }

    /**
     * Setter for <code>cms.c_user.expired</code>.
     */
    @Override
    public void setExpired(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>cms.c_user.expired</code>.
     */
    @Override
    public Long getExpired() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>cms.c_user.create_time</code>.
     */
    @Override
    public void setCreateTime(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>cms.c_user.create_time</code>.
     */
    @Override
    public Timestamp getCreateTime() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>cms.c_user.last_login_time</code>.
     */
    @Override
    public void setLastLoginTime(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>cms.c_user.last_login_time</code>.
     */
    @Override
    public Timestamp getLastLoginTime() {
        return (Timestamp) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, String, String, Long, Timestamp, Timestamp> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, String, String, Long, Timestamp, Timestamp> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return CUser.C_USER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return CUser.C_USER.USERNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return CUser.C_USER.PASSWORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return CUser.C_USER.TOKEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return CUser.C_USER.EXPIRED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return CUser.C_USER.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return CUser.C_USER.LAST_LOGIN_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getExpired();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getLastLoginTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CUserRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CUserRecord value2(String value) {
        setUsername(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CUserRecord value3(String value) {
        setPassword(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CUserRecord value4(String value) {
        setToken(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CUserRecord value5(Long value) {
        setExpired(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CUserRecord value6(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CUserRecord value7(Timestamp value) {
        setLastLoginTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CUserRecord values(String value1, String value2, String value3, String value4, Long value5, Timestamp value6, Timestamp value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ICUser from) {
        setId(from.getId());
        setUsername(from.getUsername());
        setPassword(from.getPassword());
        setToken(from.getToken());
        setExpired(from.getExpired());
        setCreateTime(from.getCreateTime());
        setLastLoginTime(from.getLastLoginTime());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ICUser> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CUserRecord
     */
    public CUserRecord() {
        super(CUser.C_USER);
    }

    /**
     * Create a detached, initialised CUserRecord
     */
    public CUserRecord(String id, String username, String password, String token, Long expired, Timestamp createTime, Timestamp lastLoginTime) {
        super(CUser.C_USER);

        set(0, id);
        set(1, username);
        set(2, password);
        set(3, token);
        set(4, expired);
        set(5, createTime);
        set(6, lastLoginTime);
    }
}
